# Generated by Django 5.2.11 on 2026-05-13 03:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_type', models.CharField(blank=True, choices=[('ie', 'IE'), ('llc', 'LLC')], max_length=10, null=True)),
                ('tax_regime', models.CharField(blank=True, choices=[('single', 'Single tax'), ('general', 'General tax regime')], max_length=15, null=True)),
                ('tin', models.CharField(blank=True, max_length=30, null=True)),
                ('taxpayer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('tax_office_code', models.CharField(blank=True, max_length=50, null=True)),
                ('tax_office_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('tax_period_type', models.CharField(blank=True, choices=[('preset', 'Preset period'), ('custom', 'Custom period')], max_length=10, null=True)),
                ('tax_period_preset', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=15, null=True)),
                ('tax_period_custom_day', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('inn', models.CharField(blank=True, max_length=20, null=True)),
                ('tax_authority_code', models.CharField(blank=True, max_length=30, null=True)),
                ('tax_authority_name', models.CharField(blank=True, max_length=255, null=True)),
                ('onboarding_status', models.CharField(choices=[('not_started', 'Not started'), ('org_type', 'Organization type'), ('tax_regime', 'Tax regime'), ('activities', 'Activities'), ('completed', 'Completed')], default='not_started', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_tax_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('non_cash_tax_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_primary', models.BooleanField(default=False)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='activities.activitycode')),
            ],
        ),
    ]
