# Generated by Django 6.0.1 on 2026-02-09 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_type', models.CharField(blank=True, choices=[('ie', 'ИП'), ('llc', 'ОсОО')], max_length=10, null=True)),
                ('tax_regime', models.CharField(blank=True, choices=[('single', 'Единый налог'), ('general', 'Общий налоговый режим')], max_length=15, null=True)),
                ('onboarding_status', models.CharField(choices=[('not_started', 'Not Started'), ('org_type', 'Org Type'), ('tax_regime', 'Tax Regime'), ('activities', 'Activities'), ('completed', 'Completed')], default='not_started', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_tax_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('non_cash_tax_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_primary', models.BooleanField(default=False)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='activities.activitycode')),
            ],
        ),
    ]
