# Generated by Django 5.2.11 on 2026-05-13 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organization', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationactivity',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='organization.organizationprofile'),
        ),
        migrations.AddConstraint(
            model_name='organizationprofile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tax_period_type__isnull', True), ('tax_period_preset__isnull', True), ('tax_period_custom_day__isnull', True)), models.Q(('tax_period_type', 'preset'), ('tax_period_preset__isnull', False)), models.Q(('tax_period_type', 'custom'), ('tax_period_custom_day__isnull', False), ('tax_period_preset__isnull', True)), _connector='OR'), name='organization_tax_period_state_valid'),
        ),
        migrations.AddConstraint(
            model_name='organizationactivity',
            constraint=models.UniqueConstraint(fields=('profile', 'activity'), name='unique_profile_activity'),
        ),
        migrations.AddConstraint(
            model_name='organizationactivity',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('profile',), name='unique_primary_activity_per_profile'),
        ),
    ]
