# Generated by Django 5.2.11 on 2026-05-13 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationprofile',
            options={'verbose_name': 'Организация', 'verbose_name_plural': 'Организации'},
        ),
    ]
