# Generated by Django 6.0.1 on 2026-02-17 08:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationprofile',
            name='tax_period_custom_day',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='День месяца для пользовательского периода (1-31)'),
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='tax_period_preset',
            field=models.CharField(blank=True, choices=[('monthly', 'Ежемесячно (1-е число)'), ('quarterly', 'Ежеквартально (1-е число)'), ('yearly', 'Ежегодно (1 января)')], max_length=15, null=True, verbose_name='Предустановленный налоговый период'),
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='tax_period_type',
            field=models.CharField(blank=True, choices=[('preset', 'Предустановленный период'), ('custom', 'Пользовательский период')], max_length=10, null=True, verbose_name='Тип налогового периода'),
        ),
    ]
