# Generated by Django 5.2.11 on 2026-04-27 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_alter_organizationactivity_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationprofile',
            name='tax_office_code',
        ),
        migrations.RemoveField(
            model_name='organizationprofile',
            name='tax_office_name',
        ),
        migrations.RemoveField(
            model_name='organizationprofile',
            name='tin',
        ),
    ]
