# Generated by Django 6.0.1 on 2026-03-25 03:25

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        ('organization', '0003_organizationprofile_tax_period_custom_day_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='organizationactivity',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='organizationprofile',
            name='onboarding_status',
            field=models.CharField(choices=[('not_started', 'Not started'), ('org_type', 'Organization type'), ('tax_regime', 'Tax regime'), ('activities', 'Activities'), ('completed', 'Completed')], default='not_started', max_length=20),
        ),
        migrations.AlterField(
            model_name='organizationprofile',
            name='org_type',
            field=models.CharField(blank=True, choices=[('ie', 'IE'), ('llc', 'LLC')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='organizationprofile',
            name='tax_period_custom_day',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='organizationprofile',
            name='tax_period_preset',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly (1st day)'), ('quarterly', 'Quarterly (1st day)'), ('yearly', 'Yearly (January 1)')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='organizationprofile',
            name='tax_period_type',
            field=models.CharField(blank=True, choices=[('preset', 'Preset period'), ('custom', 'Custom period')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='organizationprofile',
            name='tax_regime',
            field=models.CharField(blank=True, choices=[('single', 'Single tax'), ('general', 'General tax regime')], max_length=15, null=True),
        ),
        migrations.AddConstraint(
            model_name='organizationactivity',
            constraint=models.UniqueConstraint(fields=('profile', 'activity'), name='unique_profile_activity'),
        ),
        migrations.AddConstraint(
            model_name='organizationactivity',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('profile',), name='unique_primary_activity_per_profile'),
        ),
        migrations.AddConstraint(
            model_name='organizationprofile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tax_period_type__isnull', True), ('tax_period_preset__isnull', True), ('tax_period_custom_day__isnull', True)), models.Q(('tax_period_type', 'preset'), ('tax_period_preset__isnull', False), ('tax_period_custom_day__isnull', True)), models.Q(('tax_period_type', 'custom'), ('tax_period_custom_day__isnull', False), ('tax_period_preset__isnull', True)), _connector='OR'), name='organization_tax_period_state_valid'),
        ),
    ]
