# Generated by Django 5.2.11 on 2026-03-25 04:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_alter_organizationactivity_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='organizationprofile',
            name='organization_tax_period_state_valid',
        ),
        migrations.AlterField(
            model_name='organizationprofile',
            name='tax_period_preset',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=15, null=True),
        ),
        migrations.AddConstraint(
            model_name='organizationprofile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tax_period_type__isnull', True), ('tax_period_preset__isnull', True), ('tax_period_custom_day__isnull', True)), models.Q(('tax_period_type', 'preset'), ('tax_period_preset__isnull', False)), models.Q(('tax_period_type', 'custom'), ('tax_period_custom_day__isnull', False), ('tax_period_preset__isnull', True)), _connector='OR'), name='organization_tax_period_state_valid'),
        ),
    ]
