# Generated by Django 6.0.1 on 2026-02-09 11:21

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('category_type', models.CharField(choices=[('income', 'Доход (категория)'), ('expense', 'Расход (категория)')], max_length=10, verbose_name='Тип категории')),
                ('is_system', models.BooleanField(default=False, verbose_name='Системная категория')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_business', models.BooleanField(default=True, verbose_name='Относится к бизнесу?')),
                ('payment_method', models.CharField(choices=[('cash', 'Наличный расчет'), ('non_cash', 'Безналичный расчет')], max_length=10, verbose_name='Метод оплаты')),
                ('is_taxable', models.BooleanField(default=True, verbose_name='Учитывается в налоговой базе?')),
                ('transaction_type', models.CharField(choices=[('income', 'Доход'), ('expense', 'Расход')], max_length=10, verbose_name='Тип операции')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма')),
                ('description', models.TextField(blank=True, max_length=100, verbose_name='Описание')),
                ('transaction_date', models.DateField(verbose_name='Дата операции')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
    ]
