# Generated by Django 5.2.11 on 2026-05-13 03:28

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_business', models.BooleanField(default=True)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('non_cash', 'Non-cash')], max_length=10)),
                ('is_taxable', models.BooleanField(default=True)),
                ('transaction_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.TextField(blank=True, max_length=100)),
                ('transaction_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cash_tax_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('non_cash_tax_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Мягкое удаление: запись скрыта из API и отчётов, но хранится в БД.', null=True, verbose_name='Дата удаления')),
            ],
            options={
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Создание'), ('soft_deleted', 'Удаление (в корзину)'), ('restored', 'Восстановление')], max_length=20, verbose_name='Действие')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Заметка')),
            ],
            options={
                'verbose_name': 'Запись журнала транзакции',
                'verbose_name_plural': 'Журнал транзакций',
                'ordering': ['-created_at'],
            },
        ),
    ]
