# Generated by Django 6.0.1 on 2026-01-29 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_category_options_alter_transaction_options_and_more'),
        ('finance', '0002_default_categories'),
    ]

    operations = [
    ]
