# Generated by Django 6.0.1 on 2026-02-17 08:29

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        ('finance', '0004_remove_transaction_finance_tra_transac_e6908c_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transaction',
            name='amount_positive',
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', Decimal('0.01'))), name='amount_positive'),
        ),
    ]
