# Generated by Django 6.0.1 on 2026-02-08 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код (ГКЭД)')),
                ('section', models.CharField(max_length=5, verbose_name='Секция')),
                ('name', models.TextField(verbose_name='Наименование деятельности')),
            ],
            options={
                'verbose_name': 'Вид деятельности',
                'verbose_name_plural': 'Виды деятельности',
            },
        ),
        migrations.CreateModel(
            name='OrganizationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_type', models.CharField(choices=[('ie', 'ИП (Индивидуальный предприниматель)'), ('llc', 'ОсОО (Общество с ограниченной ответственностью)')], max_length=10)),
                ('tax_regime', models.CharField(choices=[('general', 'Общий налоговый режим'), ('single', 'Единый налог')], max_length=15)),
                ('cash_tax_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Ставка (наличные, %)')),
                ('non_cash_tax_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Ставка (безнал, %)')),
                ('is_onboarded', models.BooleanField(default=False)),
                ('additional_activities', models.ManyToManyField(blank=True, related_name='secondary_for', to='users.activitycode')),
                ('primary_activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_for', to='users.activitycode')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
